services:
  # Servicio de Autenticación
  db_autenticacion:
    image: mysql:9.0.1
    container_name: AutenticacionDB
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: AutenticacionDB
    ports:
      - "3306:3306"
    networks:
      - app-network

  autenticacion:
    build:
      context: ./autenticacion
    container_name: MicroservicioAutenticacion
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db_autenticacion

  # Servicio de Búsqueda
  busqueda:
    build:
      context: ./busqueda/fastAPI
    container_name: MicroservicioBusqueda
    ports:
      - "8001:8000"
    networks:
      - app-network

  # Servicio de CMS
  db_cms:
    image: nouchka/sqlite3
    container_name: CMSDB
    volumes:
      - ./cms_project/db:/data
    environment:
      - SQLITE_DATABASE=mydatabase.db
    networks:
      - app-network

  cms:
    build:
      context: ./cms_project
    container_name: MicroservicioCMS
    ports:
      - "8002:8000"
    networks:
      - app-network
    depends_on:
      - db_cms
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  # Servicio de Gestión de Post
  gestion_post:
    build:
      context: ./gestion_post
    container_name: MicroservicioGestionPost
    ports:
      - "8003:8000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge
